# Generated by Django 4.0.4 on 2022-05-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(choices=[('CAT', 'Cat'), ('DOG', 'Dog'), ('PRT', 'Parrot')], default='CAT', max_length=3, verbose_name='Вид')),
                ('name', models.CharField(max_length=127, verbose_name='Имя')),
                ('breed', models.CharField(max_length=127, verbose_name='Порода')),
                ('description', models.TextField(verbose_name='Описание')),
                ('adoption_date', models.DateTimeField(verbose_name='Дата поступления')),
            ],
        ),
    ]
