# Generated by Django 4.0.4 on 2022-06-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_pet_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('M', 'Самец'), ('F', 'Самка')], default='M', max_length=6, verbose_name='Пол'),
        ),
    ]
