# Generated by Django 4.0.4 on 2022-06-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_pet_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='age',
            field=models.CharField(default='', max_length=127, verbose_name='Возраст'),
        ),
    ]
